### ISSUE TITLE
Issue With Typescript Version above 5.5

### ISSUE THREAD

**Issue by saranshgrover** [datocms/nextjs-starter-kit#3]
As per the gql.tada [docs](https://gql-tada.0no.co/get-started/installation#prior-to-typescript-5-5), this repo is set up with the `@0no-co/graphqlsp` plugin. However, when running a fresh install for this starter, npm installs typescript version over 5.5 (`5.5.3`). For this, we should be using the default gql.tada/ts-plugin otherwise the typescript server does not pick up the queries properly and marks them as unknwon.

I am pretty certain this is why #1 was not working either.

**Comment by stefanoverna** [comment]
Thanks for the report @saranshgrover, we should have fixed the issue!
